name: CI App Integration Test

on: 
  workflow_dispatch:

# This tells the GitHub Runner to bypass the default read-only UI setting
permissions:
  contents: write
  actions: write
  checks: write
  statuses: write

jobs:
  diagnostic_build:
    name: Execute App Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: |
          echo "GitHub Actions is active."
          echo "Testing console log streaming retrieval."
